spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: after_route
            uri: https://example.org
            predicates:
              - Cookie=mycookie,mycookievalue

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: read-only

server:
  port: 8080
