spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: test
            uri: http://localhost:8080/
            predicates:
              - Path=/api/users/{id}

network:
  user-service:
    base-url: ${USERSERVICE_BASEURL}
  auth-service:
    base-url: ${KEYCLOAK_BASEURL}
    service-client:
      id: ${GATEWAY_CLIENT_ID}
      secret: ${GATEWAY_CLIENT_SECRET}
    authentication-client:
      id: ${AUTH_CLIENT_ID}
      secret: ${AUTH_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: read-only

server:
  port: 8081
  error:
    include-message: always
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: INFO
    reactor.netty: INFO
