spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # UserService routes
            - id: userservice
              uri: ${USERSERVICE_BASEURL}
              predicates:
                - Path=/api/users/**,/api/cards/**

            - id: userservice-open-api
              uri: ${USERSERVICE_BASEURL}
              predicates:
                - Path=/users/v3/api-docs
              filters:
                - StripPrefix=1

            # OrderService routes
            - id: orderservice
              uri: ${ORDERSERVICE_BASEURL}
              predicates:
                - Path=/api/orders/**,/api/items/**

            - id: orderservice-open-api
              uri: ${ORDERSERVICE_BASEURL}
              predicates:
                - Path=/orders/v3/api-docs
              filters:
                - StripPrefix=1

            # PaymentService routes
            - id: paymentservice
              uri: ${PAYMENTSERVICE_BASEURL}
              predicates:
                - Path=/api/payments/**

            - id: paymentservice-open-api
              uri: ${PAYMENTSERVICE_BASEURL}
              predicates:
                - Path=/payments/v3/api-docs
              filters:
                - StripPrefix=1


swagger-ui:
  oauth:
    issuer-uri: ${OAUTH_ISSUER_URI}

springdoc:
  show-actuator: false
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: order-service
        url: /orders/v3/api-docs
      - name: payment-service
        url: /payments/v3/api-docs
      - name: user-service
        url: /users/v3/api-docs

network:
  user-service:
    base-url: ${USERSERVICE_BASEURL}
  auth-service:
    base-url: ${KEYCLOAK_BASEURL}
    service-client:
      id: ${GATEWAY_CLIENT_ID}
      secret: ${GATEWAY_CLIENT_SECRET}
    authentication-client:
      id: ${AUTH_CLIENT_ID}
      secret: ${AUTH_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      access: read-only

server:
  port: 8081
  error:
    include-message: always
  forward-headers-strategy: framework

logging:
  level:
    com.intern.gateway.client: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: INFO
    reactor.netty: INFO
